### ISSUE TITLE
Create first event!

### ISSUE THREAD

**Issue by avilaton** [nodeschool/cordoba#3]

**Comment by sergiolepore** [comment]
+1! Do you need any help? Can I join the team? :smile:

**Comment by avilaton** [comment]
Claro que si, podes venir el sabado?

**Comment by sergiolepore** [comment]
@avilaton de una!

**Comment by sergiolepore** [comment]
Hora y lugar?

**Comment by avilaton** [comment]
Nos juntamos este sabado 19 en CreaFabLab frente a la plaza colon de 10:00 a 17:00 con unos choris al mediodía. Contactame en Twitter como @avilagas y hablamos!

**Comment by eafelix** [comment]
Buena onda chicos con la iniciativa en cordoba, cualquier ayuda q necesiten no duden en chiflar en el repo de buenos aires. 

Abrazo!

**Comment by avilaton** [comment]
El sabado hicimos una dry-run para una nodeschool con @alejandrocragnolini-santex y juntamos aprox 12 personas. Salió bastante bien. Ahora queremos organizar uno grande. Alguno ninja de uds se animaria a venir?

**Comment by sergiolepore** [comment]
@avilaton yo ya estoy más libre que la otra vez :smile: si se organiza con tiempo (una semana como mínimo) voy de unaza.

**Comment by avilaton** [comment]
Dale! si querés pasar un dia por el lab, siempre hay gente, asi podś ver el espacio. Salio tranqui, eramos todos amigos. Ahora tenemos que armar una más grande, conseguir sponsors e invitar a más gente.
